### ISSUE TITLE
License Information

### ISSUE THREAD

**Issue by shivam-bathla** [hatlord/snmpwn#5]
Hi,
Really great work guys! I really appreciate the project and the efforts you guys have put into it. We would like to use the project for a commercial training online/classroom. So, I just wanted to clarify, if we acknowledge the source, would that be sufficient and covered under the terms of use?

**Comment by hatlord** [comment]
Thanks for the change @einfallstoll - I see no reason to not use the MIT license, this is after all basically a wrapper for snmpwalk. @DeadlyHollows you are free to use the software in your training as per the license. A credit would be appreciated, along with a link to the repo. It would also be nice to know which online training this relates to if you can share that.

Thanks!

**Comment by shivam-bathla** [comment]
Thanks a lot @hatlord for accepting the license changes and @einfallstoll for helping me out on a really short notice. Really appreciate it! We had planned to use it for bruteforcing SNMPv3. But had to skip it due to the license.

Thanks!
